/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'francesco' at '10/29/13 3:34 PM' with Gradle 1.8
 *
 * @author francesco, @date 10/29/13 3:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
